      - name: Call OpenAI API via inline Python
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<EOF
          import openai
          from pathlib import Path
          import os
          import sys

          try:
              openai.api_key = os.getenv("OPENAI_API_KEY")
              prompt_path = Path("reports/prompt.txt")
              if not prompt_path.exists():
                  print("ERROR: prompt.txt not found!")
                  sys.exit(1)

              prompt = prompt_path.read_text()
              if not prompt.strip():
                  print("ERROR: prompt.txt is empty!")
                  sys.exit(1)

              print("Prompt preview (first 200 chars):")
              print(prompt[:200])

              response = openai.ChatCompletion.create(
                  model="gpt-4o-mini",
                  messages=[
                      {"role": "system", "content": "You are a helpful assistant that writes concise weekly project reports."},
                      {"role": "user", "content": prompt}
                  ],
                  temperature=0.5,
                  max_tokens=500
              )

              report_text = response.choices[0].message["content"]
              print("Response preview (first 200 chars):")
              print(report_text[:200])

              Path("reports/Weekly_Report.md").write_text(report_text)

          except Exception as e:
              print("Exception occurred:", e)
              sys.exit(1)
          EOF
