name: Weekly AI Report

on:
  schedule:
    - cron: "0 9 * * FRI"  # Every Friday at 09:00 UTC
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push commits

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests python-dateutil

      - name: Generate AI prompt with Python
        run: python .github/scripts/generate_prompt.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read AI prompt from file into env var
        run: |
          echo "PROMPT<<EOF" >> $GITHUB_ENV
          cat reports/prompt.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Call OpenAI ChatGPT
        id: chatgpt
        uses: openai/openai@v1
        with:
          model: gpt-4o-mini
          api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt: ${{ env.PROMPT }}

      - name: Save AI response as report
        run: echo "${{ steps.chatgpt.outputs.completion }}" > reports/Weekly_Report.md

      - name: Commit and push report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add reports/Weekly_Report.md
          git commit -m "chore: add weekly AI report"
          git push
