name: Weekly AI Report

on:
  schedule:
    - cron: "0 9 * * FRI"  # Every Friday at 09:00 UTC
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push commits

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests python-dateutil openai

      - name: Generate AI prompt with Python
        run: python .github/scripts/generate_prompt.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Call OpenAI API via inline Python
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<EOF
          import openai
          from pathlib import Path
          import os

          openai.api_key = os.getenv("OPENAI_API_KEY")
          prompt = Path("reports/prompt.txt").read_text()

          response = openai.ChatCompletion.create(
              model="gpt-4o-mini",
              messages=[
                  {"role": "system", "content": "You are a helpful assistant that writes concise weekly project reports."},
                  {"role": "user", "content": prompt}
              ],
              temperature=0.5,
              max_tokens=500
          )

          Path("reports/Weekly_Report.md").write_text(response.choices[0].message["content"])
          EOF

      - name: Commit and push report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add reports/Weekly_Report.md
          git commit -m "chore: add weekly AI report"
          git push
