name: Weekly Report Generator

on:
  schedule:
    - cron: '19  0 * * 1'  # Every Monday at 01:15 UTC

jobs:
  generate_and_commit_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Run report generation script
        run: |
          python your_script.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # If your script outputs to "weekly_report.md"
          git add weekly_report.md

          git commit -m "Weekly report update - $(date -u +'%Y-%m-%d')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
